### ISSUE TITLE
Mask for aurelhy

### ISSUE THREAD

**Issue by paulvija** [phgrosjean/aurelhy#1]
Hi there,

Just trying to use this interpolation technique to achieve the same result as Morocco, in my case it is New Zealand.

`library('aurelhy')
##### Read ASCII grid into a geotm object

dem_path <- './Work/Interpolation/Data/otago005_1.asc' 
nz_dem <- read.geotm(file=dem_path, type = "ascii")
##### Read ASCII grid into a geomask object

mask_path <- './Work/Interpolation/Data/otago_mask_3.asc' 
nz_mask <- read.geomask(file=mask_path, type = "ascii")
##### Read station data into a dataframe

rain_path <- './Work/Interpolation/Data/NZ_query_selection.csv' 
rain_df <- read.csv(rain_path)
##### Interpolate

maurelhy <- aurelhy(nz_dem, nz_mask)
##### Error in apply(mask, 1, any) : dim(X) must have a positive length `

![image](https://cloud.githubusercontent.com/assets/12703555/13340078/4bdab78a-dc92-11e5-8644-743109b3ff2e.png)

Note:
1. I have no hint why I get the error at aurelhy function call. What does this mean?
2. Also assuming the TRUE values in the mask as targeted area and FALSE values as not interested?
3. The way I created the mask is not correct as you can see from the terrain image. Just tried to extract a small portion with a certain cell value.

Files attached:
[NZ_query_selection.zip](https://github.com/phgrosjean/aurelhy/files/147544/NZ_query_selection.zip)

Thanks for the time and effort,

Vijay Paul

**Comment by phgrosjean** [comment]
Hi Paul,

I think the problem is that nz_dem must span over the stations plus the diameter defined in the mask. I'll have to double check, but definitely, I agree that the error message is rather useless. I have to trap this and issue a more informative error message.

Philippe
